Increase number o frameSize
Error from job

org.apache.spark.SparkException: Map output statuses were 104316083 bytes which exceeds spark.akka.frameSize (15728640 bytes).

From documentation:
Maximum message size to allow in "control plane" communication (for serialized tasks and task results), in MB. Increase this if your tasks need to send back large results to the driver (e.g. using collect() on a large dataset).

Let's try